# Run complete pipeline using conda environment
Write-Host "========================================" -ForegroundColor Yellow
Write-Host "Running complete pipeline..." -ForegroundColor Yellow
Write-Host "========================================" -ForegroundColor Yellow

# Step 1: Filter files
Write-Host ""
Write-Host "Step 1: Filtering files by date parsing..." -ForegroundColor Cyan
& "$PSScriptRoot\run_filter_files.ps1"
if ($LASTEXITCODE -ne 0) {
    Write-Host "Error: File filtering failed" -ForegroundColor Red
    exit $LASTEXITCODE
}

# Step 2: Run Python pipeline
Write-Host ""
Write-Host "Step 2: Running Python pipeline..." -ForegroundColor Cyan
& "$PSScriptRoot\run_pipeline.ps1"
if ($LASTEXITCODE -ne 0) {
    Write-Host "Error: Python pipeline failed" -ForegroundColor Red
    exit $LASTEXITCODE
}

# Note: R figures are already generated by Python pipeline for each group
# (news, raddit, news_raddit, etc.) in Step 2
# The R scripts need group-specific table directories, which are set by Python pipeline
# Running R scripts directly here would fail because tables are in subdirectories

Write-Host ""
Write-Host "========================================" -ForegroundColor Yellow
Write-Host "All tasks completed!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Yellow
Write-Host "Note: R figures were generated for each group during Python pipeline execution" -ForegroundColor Cyan

